### ISSUE TITLE
What to do if no titles?

### ISSUE THREAD

**Issue by jduss4** [open-oni/plugin_featured_content#2]
Currently the PR will break if there are no images
- Fix that
- Figure out how to present information to user if there are no titles loaded

**Comment by jduss4** [comment]
```
ValueError at /

sample larger than population
```
when RANDOM set to True and no batches loaded

**Comment by karindalziel** [comment]
Doesn't seem like too big an issue since the software is useless without batches loaded - might just want to clarify instructions. 

Something that would be useful for me would be is there was a sample json that was pulled from the oni sample batches.

**Comment by jduss4** [comment]
I think we should definitely make it so that there isn't an error if there is no content, however!
